networks:
  leconfe-network:
    driver: bridge

services:
  leconfe:
    image: leconfe/leconfe:1.1.1
    restart: unless-stopped    
    container_name: "leconfe_app_${PROJECT_NAME:-demo}"
    # env_file:
    #      - .env
    environment:
      PHP_OPCACHE_ENABLE: 1
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./volumes/public:/var/www/html/storage/app/public
      - ./volumes/private:/var/www/html/storage/app/private
      - ./volumes/plugins:/var/www/html/plugins
      - ./volumes/logs:/var/www/html/storage/logs
      - ./volumes/leconfe.env:/var/www/html/.env
    networks:
      - leconfe-network
    depends_on:
      - database
  
  # MySQL service
  database:
    image: mysql:8.0
    networks:
      - leconfe-network
    container_name: "leconfe_db_${PROJECT_NAME:-demo}"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leconfe
      MYSQL_USER: leconfe
      MYSQL_PASSWORD: leconfe
    volumes:
      - ./volumes/db:/var/lib/mysql