networks:
  leconfe-network:
    driver: bridge

services:
  leconfe:
    image: leconfe/leconfe:latest
    restart: unless-stopped    
    container_name: "leconfe_app_${PROJECT_NAME:-demo}"
    environment:
      PHP_OPCACHE_ENABLE: 1
    ports:
      - "${HTTP_PORT:-8080}:8080"
      - "${HTTPS_PORT:-8443}:8443"
    volumes:
      - ./leconfe/local:/var/www/html/storage/app/local
      - ./leconfe/public:/var/www/html/storage/app/public
      - ./leconfe/private:/var/www/html/storage/app/private
      - ./leconfe/plugins:/var/www/html/plugins
      - ./leconfe/logs:/var/www/html/storage/logs
      - ./leconfe/sessions:/var/www/html/storage/framework/sessions
      - ./leconfe/leconfe.env:/var/www/html/.env
    networks:
      - leconfe-network
    depends_on:
      - database
  
  # MySQL service
  database:
    image: mysql:8.0
    networks:
      - leconfe-network
    container_name: "leconfe_db_${PROJECT_NAME:-demo}"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leconfe
      MYSQL_USER: leconfe
      MYSQL_PASSWORD: leconfe
    volumes:
      - ./db:/var/lib/mysql